# name|window title|program|icon|default width|default height
terminal|TERMINAL|/bin/gui-terminal|terminal|570|390
files|FILES|/bin/gui-files|files|340|480
monitor|SYSTEM MONITOR|/bin/gui-monitor|monitor|390|380
editor|EDITOR|/bin/gui-editor|editor|560|430
